CREATE USER guest;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO guest;

CREATE USER editor;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO editor;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO editor;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO editor;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO editor;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO editor;
